# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace # trims trailing whitespace.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: check-json # Attempts to load all json files to verify syntax.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: mixed-line-ending # replaces or checks mixed line ending.
        args: [ "--fix=auto" ]
      - id: no-commit-to-branch
        args:
          - --branch=main
